name: Deploy Page

on:
  push:
    branches: ['master']
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true
  

jobs:
  # Build job
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Init git config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Install Dependencies Commit changes and push
        run: |
          git branch --delete gh-page || true 
          git checkout -b gh-page
          npm install
          npm run build
          
          mv public docs
          mv dist/* docs
          
          find . -type f -name "*.js" -exec sed -i 's|../dist/main.js|./main.js|g' {} +
          
          git add . || true 
          git commit -m "Build page" || true 
          git push origin gh-page --force
